id: P5E3F4C42
initial_creation_type: input
source_metadata:
  title: Jigme Lingpa Series
  language: de
  description: A series of texts by and about the great Dzogchen master Rigdzin Jigme
    Lingpa (rig 'dzin 'jigs med gling pa, 1730–1798), who revealed the Longchen Nyingtik
    (klong chen snying thig) collection.
  volume:
    06f3630b7f3f4518a319ffc389684379:
      title: An Aspiration for the Final Age
      parent: Aspiration Prayers
    1674204b9cdd4914895fc5dd7150f9be:
      title: Aspiration to Be Reborn in the Realm of Sukhāvatī
      parent: Aspiration Prayers
    b924e91635cd4dfbafe2b4a662f94c4c:
      title: 'Entering the City of Omniscience: An Aspiration Prayer for Actualizing
        Words of Truth'
      parent: Aspiration Prayers
    c18af94238ff471bb8989fa126bd80fe:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Aspiration Prayers
    7bdd1272cb934d7e9f0b30e79ee4e4dd:
      title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
      parent: Aspiration Prayers
    dd9a04e89e7443f29217e3e494b94ce5:
      title: 'Precise Discernment of Dharmas: A Catalogue of the Complete Collected
        Works of the Omniscient King of Dharma, Rigdzin Jigme Lingpa'
      parent: Catalogues
    3ac2bfeb603445f6903ea9c2a8690c5b:
      title: 'Elucidating the Body Maṇḍala: Clarifications on the Recitation Manual
        of the Female Practice of the Queen of Great Bliss'
      parent: Commentaries
    0e38f0dc07db40afa8691a10cd7ac7bc:
      title: Main Recitation Manual for the Female Practice of the Queen of Great
        Bliss
      parent: Commentaries
    63979948957a4c759d2cbddf82467a32:
      title: 'The Casket of Siddhis: A Recitation Manual for “Vidyādhara Assembly”
        (Rigdzin Düpa)'
      parent: Commentaries
    535695bea685489c9cc9dd624c872c4a:
      title: 'The Loud Drum of Spring: A Commentary on the Difficult Points of the
        Ritual of the Great Compassionate One, Natural Liberation of Suffering'
      parent: Commentaries
    6751d686f3dd4fa48b572df6255db177:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Commentaries
    8d86944dcec644dbb91bbfc369e9d7fb:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Confession
    7f17afa3285b430d90fc9e13475bd901:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: Dharma Protectors
    e1cfcef2dbb74392aef0385520d51696:
      title: Vajra Verses on the Natural State
      parent: Dzogchen
    9ebee50706c342588153577cdd4feba8:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Empowerment Rites
    10cf5992b7834dbb8ad131575ceedd8d:
      title: 'Illuminating the Meaning of Empowerment: A Self-Initiation for the Female
        Practice of the Ḍākinī'
      parent: Empowerment Rites
    2ba81d38e9e140fdb669d0b39fcf7ba6:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Empowerment Rites
    60440013462b4c54982f83215615bf3c:
      title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
      parent: Guru Rinpoche Prayers
    d0fd7fe09f574b4394ee413a69f77719:
      title: A Prayer of Devotion, to Make the Tears Fall
      parent: Guru Rinpoche Prayers
    0215a96f6cae484ba5bb554526284aea:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Guru Rinpoche Prayers
    aa29007ae12e4c1b84818db3041ab7bd:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Guru Rinpoche Prayers
    b64148de469a4d40bbf67f2eb8ac5aef:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Guru Rinpoche Prayers
    f60d33427c5444ad8d78ba461a7c8f8f:
      title: Guru Yoga of Rigdzin Jigme Lingpa
      parent: Guru Yoga
    9ec2da408a4e45688c3b6afc459c52a4:
      title: 'The Wish-Fulfilling Jewel: The Outer Practice of Guru Yoga from the
        Heart-Essence of the Vast Expanse'
      parent: Guru Yoga
    5071b5eb86b24a8dbd8bc46712a77e46:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: History
    ecf75baf660b4c5a92966235c186170b:
      title: Palchen Düpa Lineage Prayer
      parent: Lineage Prayers
    10ccc53f3d77459191b09d667550f436:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Lineage Prayers
    fb7beb7499464bb2bb662b0580e68e13:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Longchen Nyingtik
    7a597497f36647719577b740db94f016:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Ngöndro
    6e7d3bf06cf14db9b6c6d743c21d482f:
      title: 'The Kalaviṅka’s Call: A Guide to Glorious Samye Chimphu'
      parent: Pilgrimage
    669bed284b134e23abc4bbe19dd65974:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Practices
    b931123b3fe54e19841cc850d130c65f:
      title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
      parent: Practices
    13421b62e5854f24b28c6f00daae819e:
      title: Descent of Blessings of the Eight Vidyādharas
      parent: Practices
    67a768c69c95480591a330d4883f0c33:
      title: 'Excellent Intention: A Simple Fasting (Nyungne) Ritual'
      parent: Practices
    8ddf90c64271433fbd149be1358b46d1:
      title: 'Rain of Accomplishments: A Concise Fulfilment Practice for the Female
        Awareness-Holder (Yumka)'
      parent: Practices
    6599946f8f9048c9b3d726beca85258d:
      title: 'The Blissful Path of Action Tantra: A Ritual for Taking the One-Day
        Vows of a Lay Practitioner'
      parent: Practices
    596bea8b271d4f09b6486ba2197d5ee1:
      title: The Eight-Branch Offering from the Gyüluk Phurba
      parent: Practices
    e49c58b0c0c642acb8d95fbd22bd3a39:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Practices
    4ed849b9e0844b758202081f947e94bb:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Practices
    b98dd6d958f94d9ebb0b91f4c9a2a491:
      title: In Praise of Jigme Lingpa’s Pre-Eminence
      parent: Praise
    ab2aaf311eab47c3976cbe01ed308d72:
      title: In Praise of the Goddess Mārīcī (Özerchenma)
      parent: Praise
    f36d1757624b4c0dbdefca9c69e7567f:
      title: Praise of the Twelve Acts of the Buddha
      parent: Praise
    425d65770e824d02a84d821d491c55d8:
      title: A Prayer Recalling the Life and Liberation of the Great Perfection Adept
        Rangjung Dorje (‘Naturally Arisen Vajra’), Jigme Lingpa
      parent: Prayers
    f212d632d10942b388605b7affe47de3:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Prayers
    eeaf6d0e753c4f7caabc1bfcec518d1f:
      title: 'Devotion that Pierces the Heart: A Prayer to the Omniscient Jigme Lingpa'
      parent: Prayers
    de45546505df4cd487ab3b8dd79b90f9:
      title: Prayer to Rigdzin Jigme Lingpa Invoking His Previous Incarnations
      parent: Prayers
    3250267ef01244a8b043f31076295675:
      title: Prayer to the Garland of Rebirths of the Dzogchenpas of Eastern Tibet
      parent: Prayers
    c3505b1f82664656982e8c6701e022ab:
      title: 'The Vajra Verses: A Prayer of the Fierce Inner Heat'
      parent: Prayers
    f08a7d6cce704cb294e33fab27d4b778:
      title: 'The Vision: A Prayer to Ārya Avalokiteśvara'
      parent: Prayers
    68277398cd144ad6acc42a8a9255d314:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Sādhanas
    f44523da5aef4d6895ceae2790765128:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Sādhanas
    e99b55d564e14722aebef04a1490935e:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Sādhanas
    4683f9b492934c8c942ddcfd93f1bee8:
      title: 'Adornment of Lord Nāgārjuna’s Wisdom Mind: The Fourfold Maṇḍala Offering
        to Tārā'
      parent: Sādhanas
    894470feb3e8437486496de21d57e764:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Sādhanas
    9dac4897e2464b60b55494bf80f479b5:
      title: Sādhana of the Great Master Vairotsana
      parent: Sādhanas
    a5a53bbf7f9546d2845e7d422500e8d0:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Sādhanas
    1e879b3f86a5428ebc41b9fe7d668326:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Sādhanas
    b8f57a10ea8e4ee685da9939f6e054ea:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Transference (Phowa)
    2470a613d83346b3894d3dcb6a38dd78:
      title: Brief Prayer of the Feast Gathering
      parent: Tsok
    506a24539c654d79a9c88b84e078d5a1:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Tsok
    bccd243f800e400896a9b8612fac1292:
      title: Song of the Feast (Tsok Lu)
      parent: Tsok
    dc230d9432844dfc9a8fb07bdde3baa6:
      title: 'Calling the Guru from Afar: A Prayer to Jigme Lingpa'
      parent: Calling the Guru from Afar
created_at: '2022-03-01T00:07:12.485724'
last_modified_at: '2022-03-01T00:07:12.485731'
